### PR TITLE
[Finishes #163391457] create endpoint to add an intervention record

### PR DESCRIPTION
**Pull request by Rhytah**
I have created an endpoint for a user to be able to add an intervention record.
Still working on ironing out some bugs.
@Nicholus @mastula77 @HabibSentongo @richien

### CODE REVIEW

**Comment by richien** [comment]
Great progress. Keep going.

**Comment by Mastula77** [comment]
Good work, keep trying

**Comment by HabibSentongo** [comment]
This is nice, you are making steady progress.

**Review by wasswa-derick — APPROVED** [review]
Looks good to me though consider looking into making the Travis CI builds to pass.

**Comment by Rhytah** [comment]
> 
> 
> Looks good to me though consider looking into making the Travis CI builds to pass.

Thank you for the feedback, I am going to refactor my tests to solve this

**Pull request merged**
