### PR TITLE
Ch 163362512 database setup

### PR DESCRIPTION
**Pull request by Rhytah**
I have created a new folder to hold my database files. 
`database.py` contains my server connection settings
`relation_commands.py` contains commands to create the tables in the database

@richien @habibsentongo @nicholusmuwonge @mastula77

### CODE REVIEW

**Comment by HabibSentongo** [comment]
nice output, you managed the different app instances in the config file so well

**Comment by richien** [comment]
Nice work. This looks ok to me.

**Review by NicholusMuwonge — COMMENTED** [review]
consider installing dotenv and from it import loadenv to get the getenv functioning as it should

**Review by NicholusMuwonge — COMMENTED** [review]
This looks fine

**Pull request merged**
