### PR TITLE
Ft 163402142 delete an intervention record

### PR DESCRIPTION
**Pull request by Rhytah**
## What does this PR do?
Add `delete intervention` enpoint

## Description of Task to be completed?

- [x] Write unittests to test output in different scenarios

- [x] Write SQL scripts to interact with the database.

## How should this be manually tested?
After cloning the repo, cd into it and run application `$ python run.py`

- Using postman test endpoint. Enter route with record id that is to be deleted.

## Reviewers
@richien @habibsentongo

### CODE REVIEW

**Comment by HabibSentongo** [comment]
This is cleaner now, keep it up.

**Comment by richien** [comment]
I like the simplicity of how you implemented this. It makes your code easy to follow. However, consider closing your connections and cursor objects after your queries. Other than that, it's a good job you've done.

**Comment by Rhytah** [comment]
> 
> 
> I like the simplicity of how you implemented this. It makes your code easy to follow. However, consider closing your connections and cursor objects after your queries. Other than that, it's a good job you've done.

Thanks for the feedback. About closing my connections I set `autocommit =True`  so that my queries are treated as independent and  each SQL statement submitted through the database connection in `autocommit` mode will be executed in its own transaction that is implicitly committed

**Comment by Mastula77** [comment]
Your test coverage is good you have both happy tests and edge tests, that is good

**Pull request merged**
